class basicGraph {
    HttpContext _httpContext...

    // constructor
    public basicGraph(int n)...

    // add edge using adjacency vertex
    public void addEdge(int vertex, int adVertex)...

    // print adjacency list
    public void PrintAdjacencyList()...

    // create adjacency matrix
    public void CreateAdjacencyMatrix()...

    // print adjacency matrix
    public void PrintAdjacencyMatrix(int?[,] adjacencyMatrix)...

    // remove edge using adjacency vertex
    public void removeEdge(int vertex, int edge)...

    // print graph
    public void printGraph()...
}